<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="Rithesh" failures="3" tests="10" name="Test" time="43.153" errors="0" timestamp="2025-07-26T18:32:59 IST">
  <testcase classname="differentapp.LaunchApplication" name="test" time="8.366"/>
  <testcase classname="differentapp.LaunchApplication" name="test3" time="0.016">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="differentapp.LaunchApplication" name="test3" time="0.009">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="differentapp.LaunchApplication" name="test3" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at differentapp.LaunchApplication.test3(LaunchApplication.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="differentapp.LaunchApplication" name="test4" time="0.006">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="differentapp.LaunchApplication" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="differentapp.LaunchApplication" name="test4" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at differentapp.LaunchApplication.test4(LaunchApplication.java:57)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="differentapp.LaunchApplication" name="test5" time="0.002">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase classname="differentapp.LaunchApplication" name="test5" time="0.022">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase classname="differentapp.LaunchApplication" name="test5" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at differentapp.LaunchApplication.test5(LaunchApplication.java:64)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
=======
<testsuite ignored="0" hostname="Rithesh" failures="0" tests="2" name="Test" time="15.09" errors="0" timestamp="2025-07-13T18:36:55 IST">
  <testcase classname="pages.TestClass" name="logintest" time="6.81"/>
  <testcase classname="pages.TestClass2" name="logintest" time="8.602"/>
>>>>>>> b54eae38f68f498f88da10ba2f21e6be1106df1c
</testsuite> <!-- Test -->
