<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Rithesh" failures="3" tests="9" name="Test(failed)" time="31.1" errors="0" timestamp="2025-07-26T18:34:04 IST">
  <testcase classname="differentapp.LaunchApplication" name="test3" time="0.58">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="differentapp.LaunchApplication" name="test3" time="0.006">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="differentapp.LaunchApplication" name="test3" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at differentapp.LaunchApplication.test3(LaunchApplication.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="differentapp.LaunchApplication" name="test4" time="0.003">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="differentapp.LaunchApplication" name="test4" time="0.002">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="differentapp.LaunchApplication" name="test4" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at differentapp.LaunchApplication.test4(LaunchApplication.java:57)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="differentapp.LaunchApplication" name="test5" time="0.002">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase classname="differentapp.LaunchApplication" name="test5" time="0.001">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase classname="differentapp.LaunchApplication" name="test5" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at differentapp.LaunchApplication.test5(LaunchApplication.java:64)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase classname="differentapp.LaunchApplication" name="test" time="0.0">
    <ignored/>
  </testcase> <!-- test -->
</testsuite> <!-- Test(failed) -->
